### ISSUE TITLE
Custom data

### ISSUE THREAD

**Issue by victornoriega** [felixgwu/img_classification_pk_pytorch#8]
Can I use this repo to classify my own custom data, with my own labels?

**Comment by felixgwu** [comment]
Hi @victornoriega,

Unfortunately, there is no command-line argument to specify a custom dataset. 
But you may replace the train_set, val_set, test_set to some other dataset object like [torchvision.datasets.ImageFolder](https://pytorch.org/docs/stable/torchvision/datasets.html#torchvision.datasets.ImageFolder).
You may change the data augmentation and the model accordingly since all the models in the repo are taking colored 32x32 images (CIFAR format) as inputs.

Best,
Felix

**Comment by felixgwu** [comment]
I'm closing it now, but feel free to reopen it if you further questions.
